// Check User
export const CHECK_USER = 'CHECK_USER'
export const CHECK_USER_PENDING = 'CHECK_USER_PENDING'
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS'
export const CHECK_USER_FAILURE = 'CHECK_USER_FAILURE'

// Check Auth
export const CHECK_AUTH = 'CHECK_AUTH'
export const CHECK_AUTH_PENDING = 'CHECK_AUTH_PENDING'
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS'
export const CHECK_AUTH_FAILURE = 'CHECK_AUTH_FAILURE'

// Sign in
export const FETCH_SIGNIN = 'FETCH_SIGNIN'
export const FETCH_SIGNIN_PENDING = 'FETCH_SIGNIN_PENDING'
export const FETCH_SIGNIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS'
export const FETCH_SIGNIN_FAILURE = 'FETCH_SIGNIN_FAILURE'

// Logout
export const FETCH_LOGOUT = 'FETCH_LOGOUT'
export const FETCH_LOGOUT_PENDING = 'FETCH_LOGOUT_PENDING'
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS'
export const FETCH_LOGOUT_FAILURE = 'FETCH_LOGOUT_FAILURE'